function [Ux, Uy, Uz, Txx, Tyy, Tzz, Tyz, Tzx, Txy] ...
    = FDTD3D_3(Ux, Uy, Uz, Txx, Tyy, Tzz, Tyz, Tzx, Txy, ...
    dtdx ...
    , nx, ny, nz, is_model_normal, is_model_share) %#codegen

  %PE_FDTD3D_Z この関数の概要をここに記述
  %FDTD
  Ux(2:nx, :, :) = Ux(2:nx, :, :) + dtdx.density_x .* ( ...
  (Txx(2:nx, :, :) - Txx(1:nx - 1, :, :)) + ...
    (Txy(2:nx, 2:ny + 1, 1:nz) - Txy(2:nx, 1:ny, 1:nz))) + ...
    dtdx.density_x .*((Tzx(2:nx, 1:ny, 2:nz + 1) - Tzx(2:nx, 1:ny, 1:nz)));

  Uy(:, 2:ny, :) = Uy(:, 2:ny, :) + dtdx.density_y .* ( ...
    (Txy(2:nx + 1, 2:ny, 1:nz) - Txy(1:nx, 2:ny, 1:nz)) + ...
    (Tyy(:, 2:ny, :) - Tyy(:, 1:ny - 1, :))) + ...
    dtdx.density_y .* ((Tyz(1:nx, 2:ny, 2:nz + 1) - Tyz(1:nx, 2:ny, 1:nz)));

  Uz(:, :, 2:nz) = Uz(:, :, 2:nz) + dtdx.density_z .* ( ...
    (Tzx(2:nx + 1, 1:ny, 2:nz) - Tzx(1:nx, 1:ny, 2:nz)) + ...
    (Tyz(1:nx, 2:ny + 1, 2:nz) - Tyz(1:nx, 1:ny, 2:nz))) + ...
    dtdx.density_z .* ((Tzz(:, :, 2:nz) - Tzz(:, :, 1:nz - 1)));

  Txx = Txx + ...
    dtdx.C11.* (Ux(2:nx + 1, :, :) - Ux(1:nx, :, :)) + ...
    dtdx.C12.* (Uy(:, 2:ny + 1, :) - Uy(:, 1:ny, :)) + ...
    dtdx.C13.* (Uz(:, :, 2:nz + 1) - Uz(:, :, 1:nz));

  Tyy =  Tyy + ...
    dtdx.C12.* (Ux(2:nx + 1, :, :) - Ux(1:nx, :, :)) + ...
    dtdx.C11.* (Uy(:, 2:ny + 1, :) - Uy(:, 1:ny, :)) + ...
    dtdx.C13.* (Uz(:, :, 2:nz + 1) - Uz(:, :, 1:nz));

  Tzz =  Tzz + ...
    dtdx.C13.* (Ux(2:nx + 1, :, :) - Ux(1:nx, :, :)) + ...
    dtdx.C13.* (Uy(:, 2:ny + 1, :) - Uy(:, 1:ny, :)) + ...
    dtdx.C33.* (Uz(:, :, 2:nz + 1) - Uz(:, :, 1:nz));

  Tyz(2:nx, 2:ny, 2:nz) = Tyz(2:nx, 2:ny, 2:nz) + dtdx.C44(2:nx, 2:ny, 2:nz).* ( ...
    (Uz(2:nx, 2:ny, 2:nz) - Uz(2:nx, 1:ny - 1, 2:nz))) + ...
    dtdx.C44(2:nx, 2:ny, 2:nz).*((Uy(2:nx, 2:ny, 2:nz) - Uy(2:nx, 2:ny, 1:nz - 1)));

  Tzx(2:nx, 2:ny, 2:nz) =  Tzx(2:nx, 2:ny, 2:nz) + dtdx.C44(2:nx, 2:ny, 2:nz).* ( ...
    (Uz(2:nx, 2:ny, 2:nz) - Uz(1:nx - 1, 2:ny, 2:nz))) + ...
    dtdx.C44(2:nx, 2:ny, 2:nz).* ((Ux(2:nx, 2:ny, 2:nz) - Ux(2:nx, 2:ny, 1:nz - 1)));

  Txy(2:nx, 2:ny, 2:nz) =  Txy(2:nx, 2:ny, 2:nz) + dtdx.C66(2:nx, 2:ny, 2:nz).* ( ...
    (Ux(2:nx, 2:ny, 2:nz) - Ux(2:nx, 1:ny - 1, 2:nz)) + ...
    (Uy(2:nx, 2:ny, 2:nz) - Uy(1:nx - 1, 2:ny, 2:nz)));
end




 