function [Ux, Uy, Uz, Txx, Tyy, Tzz, Tyz, Tzx, Txy, Ex, Ey, Ez, tEx, tEy, tEz] ...
    = PE_FDTD3D_3(Ux, Uy, Uz, Txx, Tyy, Tzz, Tyz, Tzx, Txy, Ex, Ey, Ez, tEx, tEy, tEz ...
    , dtdx, dtdz ...
    , nx, ny, nz, rate ...
    , e, is_model_normal, is_model_share) %#codegen

  %PE_FDTD3D_Z この関数の概要をここに記述
  %FDTD
  Ux(2:nx, :, :) = Ux(2:nx, :, :) + dtdx.density_x .* ( ...
    (Txx(2:nx, :, :) - Txx(1:nx - 1, :, :)) + ...
    (Txy(2:nx, 2:ny + 1, 1:nz) - Txy(2:nx, 1:ny, 1:nz))) + ...
    dtdz.density_x .*((Tzx(2:nx, 1:ny, 2:nz + 1) - Tzx(2:nx, 1:ny, 1:nz)));

  Uy(:, 2:ny, :) = Uy(:, 2:ny, :) + dtdx.density_y .* ( ...
    (Txy(2:nx + 1, 2:ny, 1:nz) - Txy(1:nx, 2:ny, 1:nz)) + ...
    (Tyy(:, 2:ny, :) - Tyy(:, 1:ny - 1, :))) + ...
    dtdz.density_y .* ((Tyz(1:nx, 2:ny, 2:nz + 1) - Tyz(1:nx, 2:ny, 1:nz)));

  Uz(:, :, 2:nz) = Uz(:, :, 2:nz) + dtdz.density_z .* ( ...
    (Tzx(2:nx + 1, 1:ny, 2:nz) - Tzx(1:nx, 1:ny, 2:nz)) + ...
    (Tyz(1:nx, 2:ny + 1, 2:nz) - Tyz(1:nx, 1:ny, 2:nz))) + ...
    dtdz.density_z .* ((Tzz(:, :, 2:nz) - Tzz(:, :, 1:nz - 1)));

  Txx = (1 - (is_model_normal+1) * rate.normal) .* Txx + ...
    dtdx.C11(is_model_normal+1) .* (Ux(2:nx + 1, :, :) - Ux(1:nx, :, :)) + ...
    dtdx.C12(is_model_normal+1) .* (Uy(:, 2:ny + 1, :) - Uy(:, 1:ny, :)) + ...
    dtdz.C13(is_model_normal+1) .* (Uz(:, :, 2:nz + 1) - Uz(:, :, 1:nz)) + ...
    - (e(1, 1) * (meanMatrix(Ex) - meanMatrix(tEx)) + ...
    e(2, 1) * (meanMatrix(Ey) - meanMatrix(tEy)) + ...
    e(3, 1) * (meanMatrix(Ez) - meanMatrix(tEz)));

  Tyy = (1 - (is_model_normal+1) * rate.normal) .* Tyy + ...
    dtdx.C12(is_model_normal+1) .* (Ux(2:nx + 1, :, :) - Ux(1:nx, :, :)) + ...
    dtdx.C11(is_model_normal+1) .* (Uy(:, 2:ny + 1, :) - Uy(:, 1:ny, :)) + ...
    dtdz.C13(is_model_normal+1) .* (Uz(:, :, 2:nz + 1) - Uz(:, :, 1:nz)) + ...
    - (e(1, 2) * (meanMatrix(Ex) - meanMatrix(tEx)) + ...
    e(2, 2) * (meanMatrix(Ey) - meanMatrix(tEy)) + ...
    e(3, 2) * (meanMatrix(Ez) - meanMatrix(tEz)));

  Tzz = (1 - (is_model_normal+1) * rate.normal) .* Tzz + ...
    dtdx.C13(is_model_normal+1) .* (Ux(2:nx + 1, :, :) - Ux(1:nx, :, :)) + ...
    dtdx.C13(is_model_normal+1) .* (Uy(:, 2:ny + 1, :) - Uy(:, 1:ny, :)) + ...
    dtdz.C33(is_model_normal+1) .* (Uz(:, :, 2:nz + 1) - Uz(:, :, 1:nz)) + ...
    - (e(1, 3) * (meanMatrix(Ex) - meanMatrix(tEx)) + ...
    e(2, 3) * (meanMatrix(Ey) - meanMatrix(tEy)) + ...
    e(3, 3) * (meanMatrix(Ez) - meanMatrix(tEz)));

  Tyz(2:nx, 2:ny, 2:nz) = (1 - rate.share) * Tyz(2:nx, 2:ny, 2:nz) + dtdx.C44(is_model_share+1) .* ( ...
    (Uz(2:nx, 2:ny, 2:nz) - Uz(2:nx, 1:ny - 1, 2:nz))) + ...
    dtdz.C44(is_model_share+1) .*((Uy(2:nx, 2:ny, 2:nz) - Uy(2:nx, 2:ny, 1:nz - 1))) + ...
    - (e(1, 4) * (Ex(2:nx, 2:ny, 2:nz) - tEx(2:nx, 2:ny, 2:nz)) +e(2, 4) * (Ey(2:nx, 2:ny, 2:nz) - tEy(2:nx, 2:ny, 2:nz)) +e(3, 4) * (Ez(2:nx, 2:ny, 2:nz) - tEz(2:nx, 2:ny, 2:nz)));

  Tzx(2:nx, 2:ny, 2:nz) = (1 - rate.share) * Tzx(2:nx, 2:ny, 2:nz) + dtdx.C44(is_model_share+1) .* ( ...
    (Uz(2:nx, 2:ny, 2:nz) - Uz(1:nx - 1, 2:ny, 2:nz))) + ...
    dtdz.C44(is_model_share+1) .* ((Ux(2:nx, 2:ny, 2:nz) - Ux(2:nx, 2:ny, 1:nz - 1))) + ...
    - (e(1, 5) * (Ex(2:nx, 2:ny, 2:nz) - tEx(2:nx, 2:ny, 2:nz)) +e(2, 5) * (Ey(2:nx, 2:ny, 2:nz) - tEy(2:nx, 2:ny, 2:nz)) +e(3, 5) * (Ez(2:nx, 2:ny, 2:nz) - tEz(2:nx, 2:ny, 2:nz)));

  Txy(2:nx, 2:ny, 2:nz) = (1 - rate.share) * Txy(2:nx, 2:ny, 2:nz) + dtdx.C66(is_model_share+1) .* ( ...
    (Ux(2:nx, 2:ny, 2:nz) - Ux(2:nx, 1:ny - 1, 2:nz)) + ...
    (Uy(2:nx, 2:ny, 2:nz) - Uy(1:nx - 1, 2:ny, 2:nz))) + ...
    - (e(1, 6) * (Ex(2:nx, 2:ny, 2:nz) - tEx(2:nx, 2:ny, 2:nz)) +e(2, 6) * (Ey(2:nx, 2:ny, 2:nz) - tEy(2:nx, 2:ny, 2:nz)) +e(3, 6) * (Ez(2:nx, 2:ny, 2:nz) - tEz(2:nx, 2:ny, 2:nz)));




  tEx = Ex; tEy = Ey; tEz = Ez;

  Ex(2:nx, 2:ny, 2:nz) = (1 - rate.sigmaip) * Ex(2:nx, 2:ny, 2:nz) ...
    - dtdx.ip * is_model_share .* ( ...
    e(1, 1) * (Ux(3:nx + 1, 2:ny, 2:nz) - Ux(1:nx - 1, 2:ny, 2:nz)) + ...
    e(1, 2) * (Uy(2:nx, 3:ny + 1, 2:nz) - Uy(2:nx, 1:ny - 1, 2:nz)) + ...
    e(1, 4) / 2 * ((Uy(2:nx, 2:ny, 2:nz) - Uy(2:nx, 2:ny, 1:nz - 1))) + ...
    e(1, 5) / 2 * ((Ux(2:nx, 2:ny, 2:nz) - Ux(2:nx, 2:ny, 1:nz - 1))) + ...
    e(1, 6) / 2 * ((Ux(2:nx, 2:ny, 2:nz) - Ux(2:nx, 1:ny - 1, 2:nz)) + (Uy(2:nx, 2:ny, 2:nz) - Uy(1:nx - 1, 2:ny, 2:nz)))) + ...
    - dtdz.ip * is_model_share .* (e(1, 3) * (Uz(2:nx, 2:ny, 3:nz + 1) - Uz(2:nx, 2:ny, 1:nz - 1)) + e(1, 4) / 2 * (Uz(2:nx, 2:ny, 2:nz) - Uz(2:nx, 1:ny - 1, 2:nz)) + ...
    e(1, 5) / 2 * (Uz(2:nx, 2:ny, 2:nz) - Uz(1:nx - 1, 2:ny, 2:nz)));

  Ey(2:nx, 2:ny, 2:nz) = (1 - rate.sigmaip) * Ey(2:nx, 2:ny, 2:nz) ...
    - dtdx.ip * is_model_share .* ( ...
    e(2, 1) * (Ux(3:nx + 1, 2:ny, 2:nz) - Ux(1:nx - 1, 2:ny, 2:nz)) + ...
    e(2, 2) * (Uy(2:nx, 3:ny + 1, 2:nz) - Uy(2:nx, 1:ny - 1, 2:nz)) + ...
    e(2, 4) / 2 * ((Uy(2:nx, 2:ny, 2:nz) - Uy(2:nx, 2:ny, 1:nz - 1))) + ...
    e(2, 5) / 2 * ((Ux(2:nx, 2:ny, 2:nz) - Ux(2:nx, 2:ny, 1:nz - 1))) + ...
    e(2, 6) / 2 * ((Ux(2:nx, 2:ny, 2:nz) - Ux(2:nx, 1:ny - 1, 2:nz)) + (Uy(2:nx, 2:ny, 2:nz) - Uy(1:nx - 1, 2:ny, 2:nz)))) + ...
    - dtdz.ip * is_model_share .* (e(2, 3) * (Uz(2:nx, 2:ny, 3:nz + 1) - Uz(2:nx, 2:ny, 1:nz - 1)) +  e(2, 4) / 2 * ((Uz(2:nx, 2:ny, 2:nz) - Uz(2:nx, 1:ny - 1, 2:nz))) + ...
    e(2, 5) / 2 * ((Uz(2:nx, 2:ny, 2:nz) - Uz(1:nx - 1, 2:ny, 2:nz))));

  Ez(2:nx, 2:ny, 2:nz) = (1 - rate.sigmaip) * Ez(2:nx, 2:ny, 2:nz) ...
    - dtdx.ip * is_model_share .* ( ...
    e(3, 1) * (Ux(3:nx + 1, 2:ny, 2:nz) - Ux(1:nx - 1, 2:ny, 2:nz)) + ...
    e(3, 2) * (Uy(2:nx, 3:ny + 1, 2:nz) - Uy(2:nx, 1:ny - 1, 2:nz)) + ...
    e(3, 4) / 2 * ((Uy(2:nx, 2:ny, 2:nz) - Uy(2:nx, 2:ny, 1:nz - 1))) + ...
    e(3, 5) / 2 * ((Ux(2:nx, 2:ny, 2:nz) - Ux(2:nx, 2:ny, 1:nz - 1))) + ...
    e(3, 6) / 2 * ((Ux(2:nx, 2:ny, 2:nz) - Ux(2:nx, 1:ny - 1, 2:nz)) + (Uy(2:nx, 2:ny, 2:nz) - Uy(1:nx - 1, 2:ny, 2:nz)))) + ...
    - dtdz.ip * is_model_share .* (e(3, 3) * (Uz(2:nx, 2:ny, 3:nz + 1) - Uz(2:nx, 2:ny, 1:nz - 1)) +  e(3, 4) / 2 * ((Uz(2:nx, 2:ny, 2:nz) - Uz(2:nx, 1:ny - 1, 2:nz))) + ...
    e(3, 5) / 2 * ((Uz(2:nx, 2:ny, 2:nz) - Uz(1:nx - 1, 2:ny, 2:nz))));
end
